"use client";

import { Canvas, useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import ThirdPersonController from "./ThirdPersonController";
import WorldNPCs from "./WorldNPCs";
import WorldTraffic from "./WorldTraffic";
import InteractionSystem, { type InteractionTarget } from "./InteractionSystem";
import JobSystem from "./JobSystem";
import MobileJoystick from "./MobileJoystick";
import { clampNeed, defaultNeeds, needLabels, type NeedId, type Needs } from "../src/game/needs";

function Player({ position }: { position: THREE.Vector3 }) { const ref = useRef<THREE.Group>(null); useFrame((_, delta) => { if (ref.current) ref.current.position.lerp(position, Math.min(delta * 14, 1)); }); return <group ref={ref} position={position}><mesh castShadow><capsuleGeometry args={[0.4,0.9,8,16]}/><meshStandardMaterial color="#2563eb"/></mesh><mesh position={[0,0.72,0]} castShadow><sphereGeometry args={[0.28,16,16]}/><meshStandardMaterial color="#70412b"/></mesh></group>; }
function Building({position,scale,color}:{position:[number,number,number];scale:[number,number,number];color:string}){return <mesh position={position} scale={scale} castShadow><boxGeometry/><meshStandardMaterial color={color}/></mesh>}
function Palm({position}:{position:[number,number,number]}){return <group position={position}><mesh position={[0,1.2,0]}><cylinderGeometry args={[0.12,0.18,2.4,8]}/><meshStandardMaterial color="#6b4f35"/></mesh><mesh position={[0,2.45,0]}><sphereGeometry args={[0.65,8,8]}/><meshStandardMaterial color="#16803c"/></mesh></group>}
function CameraFollow({target}:{target:THREE.Vector3}){const targetRef=useRef(target.clone());useFrame(({camera},delta)=>{targetRef.current.lerp(target,Math.min(delta*10,1));const desired=new THREE.Vector3(targetRef.current.x+7,6.5,targetRef.current.z+9);camera.position.lerp(desired,Math.min(delta*4,1));camera.lookAt(targetRef.current.x,1,targetRef.current.z)});return null}
const targets:Array<InteractionTarget&{position:[number,number,number]}>= [{id:"vendor",name:"Mama Titi",type:"npc",description:"Hot jollof rice, akara and snacks near the Yaba bus stop.",action:"Eat · ₦800",position:[-3,0,2]},{id:"tech",name:"Yaba Tech Hub",type:"shop",description:"Phone repairs and electronics.",action:"Repair · ₦1,500",position:[7,0,-7]},{id:"room",name:"Your Room",type:"home",description:"Rest in your starter room and recover Energy.",action:"Sleep",position:[-7,0,5]}];
const deliveryPoint = new THREE.Vector3(6,1,8);
const needIcons:Record<NeedId,string>={hunger:"🍲",energy:"⚡",hygiene:"🧼",fun:"🎵",social:"💬"};
export default function LifeWorld(){const [playerPosition,setPlayerPosition]=useState(()=>new THREE.Vector3(0,1,4));const [characterName,setCharacterName]=useState("Goodness");const [money,setMoney]=useState(15000);const [needs,setNeeds]=useState<Needs>(defaultNeeds);const [target,setTarget]=useState<InteractionTarget|null>(null);const [showJobs,setShowJobs]=useState(false);const [mobileInput,setMobileInput]=useState({x:0,z:0});const [toast,setToast]=useState("");const [deliveryActive,setDeliveryActive]=useState(false);
useEffect(()=>{try{const saved=localStorage.getItem("life-character");if(saved){const data=JSON.parse(saved);setCharacterName(data.name||"Goodness");setMoney(data.money??15000);setNeeds(data.needs||defaultNeeds)}}catch{}},[]);
useEffect(()=>{const timer=window.setInterval(()=>setNeeds(n=>Object.fromEntries(Object.entries(n).map(([key,value])=>[key,clampNeed(value-(key==="energy"?0.18:0.1))])) as Needs),5000);return()=>window.clearInterval(timer)},[]);
useEffect(()=>{const nearest=targets.map(item=>({item,distance:playerPosition.distanceTo(new THREE.Vector3(...item.position))})).sort((a,b)=>a.distance-b.distance)[0];setTarget(nearest&&nearest.distance<3?nearest.item:null);if(deliveryActive&&playerPosition.distanceTo(deliveryPoint)<2){setDeliveryActive(false);setMoney(v=>v+3500);setToast("Delivery complete · +₦3,500");window.setTimeout(()=>setToast(""),2200)}},[playerPosition,deliveryActive]);
useEffect(()=>{try{const saved=localStorage.getItem("life-character");if(saved)localStorage.setItem("life-character",JSON.stringify({...JSON.parse(saved),money,needs}))}catch{}},[money,needs]);
const startDelivery=()=>{if(deliveryActive){setToast("Delivery already active");return false}setDeliveryActive(true);setShowJobs(false);setToast("Delivery accepted · Follow the marker to your customer");window.setTimeout(()=>setToast(""),2200);return true};
const interact=()=>{if(!target)return;if(target.id==="vendor"){if(money<800){setToast("Not enough money");return}setMoney(v=>v-800);setNeeds(n=>({...n,hunger:clampNeed(n.hunger+30),fun:clampNeed(n.fun+5)}));setToast("You ate jollof rice · -₦800")}else if(target.id==="tech"){if(money<1500){setToast("Not enough money");return}setMoney(v=>v-1500);setNeeds(n=>({...n,fun:clampNeed(n.fun+5)}));setToast("Phone repaired · -₦1,500")}else{setNeeds(n=>({...n,energy:clampNeed(n.energy+50),hygiene:clampNeed(n.hygiene-5)}));setToast("You rested · Energy restored")}window.setTimeout(()=>setToast(""),2200)};
return <div className="world-canvas"><div className="world-hud"><strong>{characterName}</strong><span>Yaba · Day 1</span><b>₦{money.toLocaleString("en-NG")}</b><div className="needs-row">{(Object.keys(needLabels) as NeedId[]).map(id=><span className="need" key={id}><i>{needIcons[id]}</i><em><small>{needLabels[id]}</small><b style={{width:`${needs[id]}%`}}/></em></span>)}</div><small className="desktop-help">WASD / Arrow keys · E to interact</small>{deliveryActive&&<small className="mission-hud">📦 Delivery active · Go to the marked customer</small>}</div><Canvas camera={{position:[7,6.5,13],fov:50}} shadows><ambientLight intensity={1.5}/><directionalLight position={[5,10,5]} intensity={2} castShadow/><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[40,40]}/><meshStandardMaterial color="#24352d"/></mesh><mesh position={[0,.03,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[6,40]}/><meshStandardMaterial color="#252b31"/></mesh><mesh position={[0,.04,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[.12,40]}/><meshStandardMaterial color="#f5c542"/></mesh><Building position={[-7,2,-5]} scale={[3,4,3]} color="#b66b3f"/><Building position={[7,2.5,-7]} scale={[3.5,5,2.8]} color="#526b7d"/><Building position={[-7,1.5,5]} scale={[3,3,2.5]} color="#d3a35d"/><Building position={[7,1.8,5]} scale={[3,3.6,3]} color="#7b4f66"/><Palm position={[-4,0,-1]}/><Palm position={[4,0,2]}/><Palm position={[-4,0,8]}/><WorldNPCs/><WorldTraffic/>{deliveryActive&&<group position={deliveryPoint.toArray()}><mesh position={[0,1.5,0]}><cylinderGeometry args={[0.55,0.55,0.15,32]}/><meshStandardMaterial color="#f97316" emissive="#f97316" emissiveIntensity={1.5}/></mesh><mesh position={[0,2.2,0]}><sphereGeometry args={[0.28,16,16]}/><meshStandardMaterial color="#ffffff" emissive="#ffffff" emissiveIntensity={1}/></mesh></group>}<Player position={playerPosition}/><ThirdPersonController position={playerPosition} onMove={setPlayerPosition} mobileInput={mobileInput}/><CameraFollow target={playerPosition}/></Canvas><InteractionSystem target={target}/><MobileJoystick onMove={(x,z)=>setMobileInput({x,z})}/>{target&&<button className="mobile-action" onClick={interact}>E</button>}<button className="jobs-toggle" onClick={()=>setShowJobs(v=>!v)}>💼 Hustles</button>{showJobs&&<JobSystem money={money} onEarn={amount=>setMoney(v=>v+amount)} onStartDelivery={startDelivery}/>}  {toast&&<div className="game-toast">{toast}</div>}</div>}
